### ISSUE TITLE
WDG: Rule Issues

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#1002]
[Flayers](https://www.the-ninth-age.com/community/lexicon/index.php?entry/2201-flayers/) do not have [Hard Target](https://www.the-ninth-age.com/community/lexicon/index.php?entry/3315-hard-target/).

Release The Hounds rule for WotDG [Warhounds](https://www.the-ninth-age.com/community/lexicon/index.php?entry/2199-warhounds/) is wrong and needs a copy and paste.

**Comment by Vrenel** [comment]
Solved and merged into Master
