### ISSUE TITLE
Mounts counting towards a different organisation category

### ISSUE THREAD

**Issue by beckian** [BSData/The-9th-Age#119]
Hello,

I have been updating the Vermin data file but do not know how to make the monstrous rat, doom bell or plague pendulum count towards the built and bred category instead of characters. Does anyone know how to solve this?

Thanks

**Comment by Karanadon** [comment]
Just take a look at one of the other files, Saurian ancient is a good contender. You have to have a separate entry for the mount, and link between the character and the mount with a shared entry.

**Comment by beckian** [comment]
Thanks, I have now applied that method to the Vermin (I think)
