### ISSUE TITLE
[Anon] Bug report: 2.0 Kingdom of Equitaine.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#125]
**File:** 2.0 Kingdom of Equitaine.catz

**BattleScribe version:** 2.00.03

**Platform:** Windows

**Dropbox:** No

**Description:** There are no costs for the "Hippogriff" of the Duke (Mounts). Normal costs 260pts.

**Comment by Karanadon** [comment]
You have to select the mount seperately under he airborne gallantry section.
