### ISSUE TITLE
[Anon] Bug report: Sylvan Elves - Oaken Crown.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#131]
**File:** Sylvan Elves - Oaken Crown.catz

**BattleScribe version:** 2.00.09

**Platform:** Mac

**Dropbox:** Yes

**Description:** Please make a proper work before uploading next time! If you are not ready, just wait!

**Comment by Karanadon** [comment]
Wow thanks for the glowing review! Can you please let us know exactly what is wrong with our files? We have many users and none have reported any errors in any files in over a week.
