### ISSUE TITLE
[Anon] Bug report: Sylvan Elves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#132]
**File:** Sylvan Elves.catz

**BattleScribe version:** 2.00.09

**Platform:** Mac

**Dropbox:** Yes

**Description:** Please make a proper work next time! If you do not have time to make it proper, just use more time! Or do not do it at all.

**Comment by Karanadon** [comment]
Wow thanks for the glowing review! Can you please let us know exactly what is wrong with our files? We have many users and none have reported any errors in any files in over a week.
