### ISSUE TITLE
[Anon] Bug report: 2.0 Sylvan Elves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#134]
**File:** 2.0 Sylvan Elves.catz

**BattleScribe version:** 2.00.16

**Platform:** Android

**Dropbox:** No

**Description:** Sylvian Elvis Pathfinder Hero cost is 315, should be 150 + 75

**Comment by Arturius1** [comment]
This Elvis is listed as Chieftain on Foot - Pathfinder Kindred (225pts) and is correct.
Thanks for report!
