### ISSUE TITLE
[Anon] Bug report: 2.0 Warriors of the Dark Gods.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#135]
**File:** 2.0 Warriors of the Dark Gods.catz

**BattleScribe version:** 2.00.21

**Platform:** Android

**Dropbox:** Yes

**Description:** Points are incorrect on Third Eye for Deamon Prince.

**Comment by Arturius1** [comment]
Thanks!

Fixed in release 1.3.18
