### ISSUE TITLE
[Anon] Bug report: 2.0 Daemon Legions of Change.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#136]
**File:** 2.0 Daemon Legions of Change.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I am attempting to add ANY form of unit to the roster, it says the maximum I can have of any slot is 0 points. Fix..?

**Comment by Karanadon** [comment]
This is an old bug that should have been fixed in the latest iOS release. Please reinstall and make sure you have the latest data files and try again. I cannot replicate the error on Android or PC.
