### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Mikel2311** [BSData/The-9th-Age#138]

**Comment by Arturius1** [comment]
@amis92  - could you please add @Mikel2311 to Data Authors - The 9th Age ?
He is a verified person, already known to our gaming and data group.
I cannot do it due to "Only organization owners can send invitations" error.

**Comment by amis92** [comment]
Sure, done.

About that error, well, not much I can do, I won't grant owner permissions to every team manager. I wish I could give you all permission to invite new members but oh well. Maybe sometime in future. :)
