### ISSUE TITLE
[Anon] Bug report: 2.0 Saurian Ancients.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#140]
**File:** 2.0 Saurian Ancients.catz

**BattleScribe version:** 2.00.11

**Platform:** Windows

**Dropbox:** No

**Description:** Saurian warrior's totem animals cost 2/model, but it's listed as free.

**Comment by Karanadon** [comment]
It's listed as free, but when you select it the cost of each saurian warrior will increment by 2 accordingly.
