### ISSUE TITLE
DL Monotheistic Dark God's Might and Dark God's Might Characters not working

### ISSUE THREAD

**Issue by vegetable** [BSData/The-9th-Age#144]
Simply adding a General Weaver, gives error on roster (osx, 9th age v39,  v5 of Monotheistec Change)
![screenshot1](https://fotos.subefotos.com/cdcfa60008d67314cd37de27724db99co.png)
![screenshot2](https://fotos.subefotos.com/0751dc274cdf8a4a87e8755460750e2co.png)
![screenshot3](https://fotos.subefotos.com/21683fdb84a504224eb1aa643db9c8eco.png)

**Comment by vegetable** [comment]
I've tried to figure out on datafiles what's wrong, and found that several categories have a repeated id (dark god's might for instance, is repeated with infernal dwarves bind and bound)

Don't know if that's where the problem is

**Comment by Karanadon** [comment]
Hi,
A few people are having similar issues with other datafiles. I cannot replicate the error on the latest PC or Android versions so I believe it is an error specifically with OSx and IOS. Are you able to test the issue on another platform?

**Comment by vegetable** [comment]
On Android I get the same error



desde mi 4ndr01d

**Comment by vegetable** [comment]
![screen1](https://fotos.subefotos.com/8005501ba288efc29e6878fbcdc31282o.png)

![screen2](https://fotos.subefotos.com/5ad7f3bab1bb380f8713688b11f73765o.png)

![screen3](https://fotos.subefotos.com/8ba4b20e24443986ff2101e40fa399a8o.png)

**Comment by Karanadon** [comment]
Should be fixed now.
