### ISSUE TITLE
[Anon] Bug report: 2.0 Undying Dynasties.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#150]
**File:** 2.0 Undying Dynasties.catz

**BattleScribe version:** 2.00.34

**Platform:** Android

**Dropbox:** No

**Description:** Royal Sphinx is "No cost", should be "400pts.
Magical item Vanquisher Eternal can be taken on mounted character, what is permitted

**Comment by Karanadon** [comment]
You should be able to find the Royal Sphinx in the "Large Mounts" Category.

Will look into Vanquisher Eternal item...
