### ISSUE TITLE
[Anon] Bug report: 2.0 The Vermin Swarm.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#157]
**File:** 2.0 The Vermin Swarm.catz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** where is the dreadmill ? Has it been removed or what is going on ?

**Comment by Arturius1** [comment]
It has been removed by recent software update. We are working on bringing it back.
