### ISSUE TITLE
[Anon] Bug report: Empire_of_Sonnstahl.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#16]
**File:** Empire_of_Sonnstahl.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** The Field Marshal incorrectly has the Legendary Warrior special rule. It may be the reason why the app gives a roster error saying that the Heavy Infantry Battalion must be upgraded to veterans.
Also would be nice to add the Cleric Apprentice upgrade to Worshippers when an High Cleric is present in the army. 
Cheers, and good work guys, really appreciate your work!

**Comment by bombastian2000** [comment]
just published fixes for these issues.
