### ISSUE TITLE
[Anon] Bug report: 2.0 Fantasy Battles The 9th Age.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#160]
**File:** 2.0 Fantasy Battles The 9th Age.gstz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Only can take 3 selections ''Characters, Special and another random'', the rest do not appear in the selection. Many Thanks.

**Comment by Karanadon** [comment]
Which army is this for?
