### ISSUE TITLE
[Anon] Bug report: 2.0 Vampire_Covenant.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#161]
**File:** 2.0 Vampire_Covenant.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Can only see uncharacterised, the suffering and swift death when making lists. Tried the usual deleting everything and reinstalling app.

**Comment by Arturius1** [comment]
Should be fixed in the next release!
