### ISSUE TITLE
SE Magic standards not counting towards core points allowance

### ISSUE THREAD

**Issue by nick-lironi-irvine** [BSData/The-9th-Age#163]
To reproduce (I'm sure there are other ways, but this is how I found it)

Create a Sylvan Elf roster of 4500 points
Add the following units
8 Dryads
8 Dryads
17 Forest Guard, Sylvan Blades,  Champion, Musician, Standard
29 Forest Guard, Spears + Shields, Champion, Musician, Standard, Veteran Standard **with War Standard**

This totals 1140 points for Core, all good. However, there is a validation error saying "must spend 15pts more from Core (minimum 1125pts)"
What is happening is that the cost of the War Standard (30 points) is being counted towards the units total cost / core points displayed in the UI, but not when calculating the percentages in Core - the validation thinks that 1140 - 30 = 1110 points (15 less than the 1125 required) has been spent on Core.

I assume the cause is something to do with the standards being linked shared selection entries but it's not clear to me if the problem is with the config file or a bug in battlescribe itself (the issue manifests in both the desktop and android app) - In the previous versions of the file and app this did not occur.

**Comment by Karanadon** [comment]
Should hopefully be working in next release.

**Comment by nick-lironi-irvine** [comment]
Thanks, that does fix the problem BUT opening existing lists now treats them as if they were oaken throne variants (and therefore breaks them) - I assume this is because the catalogue Id was changed as part of the fix and shouldn't have been?

**Comment by Karanadon** [comment]
The catalog ID shouldn't have been changed, so not sure what is happening! Will take a look and see what I can find.
