### ISSUE TITLE
[Anon] Bug report: 2.0 Saurian Ancients.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#169]
**File:** 2.0 Saurian Ancients.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** Yes

**Description:** The caiman armor save is incorrect when you view the roster. It should be 4+  Also, the Alpha Carnosaur stats do not show up in the roster view when I select it as a mount for a firstborn warlord

**Comment by Karanadon** [comment]
Fixed
