### ISSUE TITLE
VC little problems

### ISSUE THREAD

**Issue by GrammyTraore** [BSData/The-9th-Age#171]
Hello!

I have just tried to build myself a roster and found 2 little things:
- Vampire courtier are limited to 100 points of magical items and it is limited to 10 in BS
- The dark coach blood ties options (stubborn) is not present

**Comment by Karanadon** [comment]
These are both fixed in v28 of the VC file.

**Comment by dacloutier** [comment]
I'm having the bloodties issue on the black coach with version v30 of the vampire covenants.

I'm also having a bloodties issue with the Blood Knights. It automatically selects it even though I chose VonKarsteins and I can't remove it.

**Comment by dacloutier** [comment]
V31 has the same issues
