### ISSUE TITLE
[Anon] Bug report: 2.0 Dread Elves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#173]
**File:** 2.0 Dread Elves.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** Hi,

I Think There  are some DE units missing: Scouts, artillery, 2nd chariot with horses
Nevertheless awesom job!

**Comment by Karanadon** [comment]
Hi, 
Please make sure you have both the DE catalog AND the DE force organization selected.
