### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by rzmoz** [BSData/The-9th-Age#178]
Hi, I play 9th age and would like to contribute to fix issues in data files for v2.0+. 

I already have the first minor fix pending which is the Exalted Herald. I currently has Manifestation min = 2 but they're chosen during spell selection thus should not be mandatory selections at the very least similar as you only choose spell path and not the final spells

**Comment by Karanadon** [comment]
Hey.
We already have a pretty solid team, and most of the work has been done for the new edition.
If you still wish to help, you can fork this repository and make pull requests with any changes. Just make sure you describe what your pull request is fixing in detail, and it does not clash with existing files.

**Comment by rzmoz** [comment]
Great, I'll do that then.
