### ISSUE TITLE
[Anon] Bug report: Orcs and Goblins 2.0 Beta.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#182]
**File:** Orcs and Goblins 2.0 Beta.catz

**BattleScribe version:** 2.01.11

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Goblin raiders: cost 165 points, should be 120, in the individual option it says 120 for 5, but total in army roster comes out at 165 for 8 and can’t be changed down to 5 models.

**Comment by Mikel2311** [comment]
I think you might be selecting the option for goblin raiders in core. Try selecting raiders in special to get 5-7 models.
