### ISSUE TITLE
[Anon] Bug report: Undying Dynasties 2.0 Beta.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#184]
**File:** Undying Dynasties 2.0 Beta.catz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** in barrow legion scarabs miss the otherwordly enhancwment and cap

**Comment by Karanadon** [comment]
They are definitely there. Try making sure you select Lord of the Barrow Legion before adding other units.
