### ISSUE TITLE
[Anon] Bug report: 1.3 Fantasy Battles The 9th Age.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#186]
**File:** 1.3 Fantasy Battles The 9th Age.gstz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** In the stat block n°2 (defensive stats) the armor save and special saves never update when you buy equipments, neither ordinary nor magical, for characters as well as troops. Can be fixed or it's a messy work? Thanks for your great and precious work guys

**Comment by Karanadon** [comment]
Very messy work I'm afraid, would take hours and hours of conditional changes, especially for characters.
Definitely not going to be implemented anytime soon.
