### ISSUE TITLE
[Anon] Bug report: Undying Dynasties 2.0 Beta.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#190]
**File:** Undying Dynasties 2.0 Beta.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** In terracotta list the charnel catapult points are still 200 instead of 215.
Thank you so much for your work!!!

**Comment by Karanadon** [comment]
Fixed with commit 7a64d3fdc259fd548b3ec5c3538a7cf33420aad9
