### ISSUE TITLE
[Anon] Bug report: Dwarven Holds 2.0 Beta.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#203]
**File:** Dwarven Holds 2.0 Beta.catz

**BattleScribe version:** 2.01.11

**Platform:** Windows

**Dropbox:** No

**Description:** I used 1335 pts for characters in a 4495 pts army and Battlescribe says that my army is invalid because I've spent 315 to much on characters (maximum 1800).

**Comment by Arturius1** [comment]
It's the new battlescribe 2.01.x issue, please use older software version.
