### ISSUE TITLE
[Anon] Bug report: 1.3 Sylvan Elves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#213]
**File:** 1.3 Sylvan Elves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The points cost for unseen arrows are twice as high as the cost per model.

**Comment by DarkSkyT9A** [comment]
Should be fixed with latest update. Please close @Arturius1 as I don't have the necessary rights to close issues
