### ISSUE TITLE
[Anon] Bug report: Orcs and Goblins 2.0 Beta.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#215]
**File:** Orcs and Goblins 2.0 Beta.catz

**BattleScribe version:** 2.00.00

**Platform:** Android

**Dropbox:** Yes

**Description:** Big brother giant. 
I can chose only normal giant and not upgrade to big Brothers

**Comment by DarkSkyT9A** [comment]
@Arturius1 is fixed. Issue should be closed.
