### ISSUE TITLE
[Anon] Bug report: Sylvan Elves 2.0 Beta.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#226]
**File:** Sylvan Elves 2.0 Beta.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** Sylvan Elves: Sylvan Sentinels. Battlescribe allows you to include these in your army even if you have not chosen any Pathfinders, contrary to the restrictions in the army book (p. 55 of the full version of the book).

**Comment by Karanadon** [comment]
Read the book again. 
Normally you can take two units of sentinels, if you take 2 pathfinders you can only have one unit of sentinels.
