### ISSUE TITLE
[Anon] Bug report: Daemon Legions 2.0.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#230]
**File:** Daemon Legions 2.0.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** hi, thank you for your work, before everything else!
Hope harvester option Engine of damnation does not work. should be a box for the 200pts one time add on, now is a multiple add device like the one for the number of models in a unit.

**Comment by DarkSkyT9A** [comment]
This has been fixed in DL 2.0 v17. Please close @Arturius1
