### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by IvoCrnkovic** [BSData/The-9th-Age#234]
Hi I'd like to join the 9th age repo to start contributing towards keeping it up to date!

**Comment by Arturius1** [comment]
Hey @IvoCrnkovic  !

Do you have an account on the 9th age forum?
https://www.the-ninth-age.com/index.php?board-list/

It is there that we coordinate all the updates and receive error reports from users.

If not you could still contribute, but it would be a little harder. :)

**Comment by IvoCrnkovic** [comment]
I dont have an account, but i could easily make one if that makes things easier.  I've been lurking the forums for a while anyway.

ill go make one and update when i have one.

**Comment by IvoCrnkovic** [comment]
I've made an account under Ivo.Crnkovic on the official forums.  Whats the next step?

**Comment by Arturius1** [comment]
Good! I will sort you out on 9th Age forum and in the meantime please write a join request here https://github.com/BSData/bsdata/issues

You first have to be a BSData member so I can add you to 9th Age repository team.
Sorry for such formalities !

**Comment by amis92** [comment]
No need, @Arturius1, just mention me here. Also, https://github.com/BSData/bsdata/issues is no longer the correct place to raise Join Requests, now https://github.com/BSData/catalogue-development is the one (for new repos), and for old, still an issue in the corresponding repo (in this case, here, this issue is correct).

**Comment by DarkSkyT9A** [comment]
Hi I'd like to join the 9th age repo to start contributing towards keeping it up to date!

**Comment by amis92** [comment]
@DarkSkyT9A this should've been a new issue opened by you.
