### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by duxbuse** [BSData/The-9th-Age#24]
Hey guys I'm interested in helping update the army books

**Comment by amis92** [comment]
@Toreador13, you want help? :)

**Comment by Toreador13** [comment]
That would entirely be @bombastian2000 's call. I am a small cog in a big machine here. Too much real life work lately for me to jump in on the files. But soon hopefully.

**Comment by amis92** [comment]
@duxbuse I sugest you start work by forking and doing a pull request, and after the first one we'll be glad to have you in. :)

Deal?

**Comment by duxbuse** [comment]
OK cheers fellas. Pull request lodged :)

**Comment by amis92** [comment]
So @Arturius1 I guess we can add @duxbuse to the team? I'm sending invite right now.
