### ISSUE TITLE
[Join Request ]

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#243]
Hi, I would like to join the team so I can manage the issues and create wiki pages to document the file structure and best practices for the team

**Comment by Arturius1** [comment]
@amis92 , please add @DarkSkyT9A since I do not have necessary rights to do this.

**Comment by amis92** [comment]
@Arturius1 I've granted admin rights to you, you can do that now at https://github.com/BSData/The-9th-Age/settings/collaboration

**Comment by Arturius1** [comment]
Thank you, it's all sorted out now.
