### ISSUE TITLE
VC: Some options for characters are double counted

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#246]
When creating some VC lists I get a notification that my Character allowance is over limit when it's below 1800. Any idea whats causing this?
Double counting price for some imtems or special abilities.If you spot which ones I can fix it.
A little bit of trial and error and it looks like the lesser blood powers that are being double counted.
This issue looks like it's still running (at least for Eternal Duelist)

**Comment by artur-fijalkowski** [comment]
There is some additional issue with Blood Powers. I need to find my notes about what was it...
