### ISSUE TITLE
9th Age tool support

### ISSUE THREAD

**Issue by Arturius1** [BSData/The-9th-Age#25]
Hello!
I'm part of the 9th age tool support team and need access to the repo. please add me.

Arturius on 9th Age forum

**Comment by amis92** [comment]
@Toreador13 can you confirm?

**Comment by Toreador13** [comment]
Confirmed @amis92 , he should be on this team.

**Comment by Arturius1** [comment]
Thanks @Toreador13 

@amis92 if you would be so kind to give me write access - I have two files updated, ready to be synced

**Comment by Toreador13** [comment]
Is @JimmyMalmer still on the team? He has the ability to assign team members. @bombastian2000, @arturius1 has updated some files to be merged. Does anyone need to ok this for the merge? I don't want to step on any feet here. Work is killing me so I haven't been able to get to the files, but maybe should be able to by the weekend.

**Comment by JimmyMalmer** [comment]
I am not in any way active in this project at the moment, so no ok from me needed. Do anyone need rights or something from me?

________________________________
Från: Toreador13 <notifications@github.com>
Skickat: den 23 mars 2016 17:23
Till: BSData/The-9th-Age
Kopia: JimmyMalmer
Ämne: Re: [The-9th-Age] 9th Age tool support (#25)


Is @JimmyMalmer<https://github.com/JimmyMalmer> still on the team? He has the ability to assign team members. @bombastian2000<https://github.com/bombastian2000>, @arturius1<https://github.com/arturius1> has updated some files to be merged. Does anyone need to ok this for the merge? I don't want to step on any feet here. Work is killing me so I haven't been able to get to the files, but maybe should be able to by the weekend.

-

**Comment by Toreador13** [comment]
@JimmyMalmer could you assign one of us team maintainer rights? Or add @Arturius1 to the team? I don't have the rights to do this, but you should.

**Comment by gommo** [comment]
I've also completed the Orc book except updating common magic items. Can someone merge that pull request next

**Comment by Toreador13** [comment]
We will have to sort out administration of this repository first. Once we get that figured out we will work out how to get stuff merged. Is the Orc list based off of the previous just with changes? It's easier to look at changes in the merge script that way for the previous maker.

**Comment by gommo** [comment]
Yep, that's right. I forked the repo

On Thursday, 24 March 2016, Toreador13 <notifications@github.com> wrote:

> We will have to sort out administration of this repository first. Once we
> get that figured out we will work out how to get stuff merged. Is the Orc
> list based off of the previous just with changes? It's easier to look at
> changes in the merge script that way for the previous maker.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/BSData/The-9th-Age/issues/25#issuecomment-200516693>
>


-- 
Sent from iPhone

**Comment by Toreador13** [comment]
I will wait until later tonight before doing a push, but merged that . @Arturius1 also has some merges, but one file is something I don't maintain and would rather have @bombastian2000 merge.

**Comment by JimmyMalmer** [comment]
I just promoted you to team maintainer, Toreador.


________________________________
Från: Toreador13 <notifications@github.com>
Skickat: den 23 mars 2016 20:20
Till: BSData/The-9th-Age
Kopia: JimmyMalmer
Ämne: Re: [The-9th-Age] 9th Age tool support (#25)


@JimmyMalmer<https://github.com/JimmyMalmer> could you assign one of us team maintainer rights? Or add @Arturius1<https://github.com/Arturius1> to the team? I don't have the rights to do this, but you should.

-

**Comment by Toreador13** [comment]
Thanks @JimmyMalmer for your help.

**Comment by amis92** [comment]
Ahh yes, unfortunately for some reason they (GutHub) don't allow team maintainers to invite people to org.

Doing this now. Cheers!
