### ISSUE TITLE
DL 2-1

### ISSUE THREAD

**Issue by Theokrit** [BSData/The-9th-Age#256]
DL File is still on version 2.0. To change to 2.1 change the following:
Rules Changes:
Piercing Spike gives now also +1 AP
Omen has Def 7. Divine Right changed a bit
Kuulimas Deceiver has Poison Attacks
Dominion of Lust, +2″ March Rate replaced with Strider.
• Maw of Akaan, AP: 1 ↗ 2.
• Dominion of Sloth, Aegis (4+) replaced with Aegis (+1).
• Vanadra’s Scourge, The Path of Dal-Magoth, Spectral Blades replaced with Ancestral Aid.
• Imps, gains Aegis (3+, against Shooting Attacks) and access to the Charged Tendrils Manifestation.
• Myrmidons, Def: 3 ↗ 4, Str 4 ↗ 5, Agi 3 ↗ 4, gain Fight in Extra Rank, lose the +2 Str in the Devastating Charge, lose access to Greenfire
Eyes, but gain access to Piercing Spike.
• Titanslayer Chariot, Adv and Mar: 6″ ↗ 7″, Mountain Breaker gives +2″ instead of +1D3″, Myrmidon same update as the core entry.
• Hoarders, Def: 6 ↘ 5, lose access to Tar Skin, gain access to Dextrous Tentacles.
• Bloat Flies, HP: 5 ↘ 4, Att: 2 ↗ 3, Str: 5 ↘ 4, AP: 1 ↗ 3, Agi: 1 ↗ 3, gains Fortitude (5+), Fly (8″, 12″) → Fly (7″, 14″), Acid Blood causes 2 hits instead of 1 per Health Point lost, Broodmother can be taken on top of other Manifestations.

All the Dominions changed (are now special rule for the character itself), and General made it also necessary to take greater Dominion (additional point cost and can give his dominion to others)

Point Changes:
Manifestations:
Brimstone 35 --> 30
Dominant 65 --> 55
Charged Tendrils 30--> 25
Chitinous Scales 30 --> 25
Clooven Hooves 40 --> 30
Hammer Hand 35 --> 40
Iron Husk 60 --> 85
Sorc Antennae 45 --> 40
Third Eye 35--> 20
Envy
Venom Sacs Guiding 65 --> 75
Greenfire Eyes 35 --> 25
Piercing Spike 25 --> 45; Guiding 45 --> 70
Greed
– Smothering Coils, Guiding 45 ↗ 50
– Divining Snout: Standard 35 ↘ 25, Guiding 55 ↘ 35
– Grasping Proboscis: Standard 15 ↘ 10, Guiding 30 ↘ 15
• Manifestations of Lust:
– Roaming Hands, Standard 40 ↘ 35
– Hot Blood: Standard 15 ↘ 10, Guiding 35 ↘ 25
• Manifestations of Pride:
– Bronze Backbone: Standard 50 ↗ 55, Guiding 75 ↗ 85
– Horns of Hubris: Standard 30 ↘ 25, Guiding 40 ↘ 35
• Manifestations of Sloth:
– Chilling Yawn 75 ↗ 85
– Segmented Shell: Standard 35 ↘ 30, Guiding 50 ↘ 40
• Manifestations of Wrath:
– Red Haze: Standard 35 ↗ 45, Guiding 70 ↗ 90
– Incendiary Ichor 15 ↘ 10
• Omen of Savar:
– Starting cost 395 ↗ 490
– Throne of Overwhelming Splendour 330 ↘ 200
• Kuulima’s Deceiver:
– Greater Dominion 40 ↘ 30
– Wizard Adept 70 ↘ 65
– Wizard Master 200 ↘ 190
– Fly and Light Troops 60 ↘ 45
• Maw of Akaan, Starting cost 610 ↘ 565
• Miser of Sugulag, Starting cost 695 ↘ 670
• Courtesan of Cibaresh:
– Starting cost 580 ↘ 575
– Greater Dominion 45 ↘ 35
• Sentinel of Nukuja:
– Starting cost 675 ↘ 620
– Greater Dominion 40 ↘ 30
– Strixian Spirit 25 ↘ 20
• Vanadra’s Scourge:
– Starting cost 790 ↘ 705
– Greater Dominion 40 ↘ 35
– Wizard Apprentice 30 ↘ 25
– Wizard Adept 105 ↘ 85
– Wizard Master 180 ↘ 130
• Harbinger of Father Chaos:
– Dark Pulpit 85 ↘ 55
– Pale Horse 85 ↘ 75
– Burning Wheel 120 ↘ 90
• Great Beast of Prophecy, Fly and Light Troops 105 ↘ 65
• Imps:
– Starting cost 235 ↘ 215
– Additional models 20/model ↘ 15/model
– Darkhide 4/model ↘ 3/model
– Incendiary Ichor 2/model ↘ 1/model
– Charged Tendrils 30
• Succubi:
– Starting cost 215 ↘ 205
– Additional models 19/model ↘ 18/model
– Chilling Yawn 5/model ↘ 4/model
– Smothering Coils 5/model ↗ 6/model
– Darkhide 2/model ↘ 1/model
– Mesmerising Plumage 2/model ↘ 1/model
• Lemures:
– Additional models 26/model ↗ 27/model
– Venom Sacs 3/model ↘ 2/model
– Brimstone Secretions 2/model ↘ 1/model
• Myrmidons:
– Starting cost 215 ↘ 205
– Additional models 21/model ↘ 20/model
– Maximum size 25/model ↗ 30/model
– Piercing Spike 5/model
– Unhinging Jaw 3/model ↘ 2/model
– Whipcrack Tail 3/model ↘ 2/model
– Hot Blood 2/model ↘ 1/model
• Eidolons:
– Starting cost 225 ↘ 200
– Additional models 45/model ↘ 37/model
– Aura of Despair 6/model ↘ 4/model
– Incendiary Ichor 2/model ↘ 1/model
– Sorcerous Antennae 45 ↘ 35
• Hellhounds:
– Starting cost 155 ↗ 165
– Additional models 21/model ↘ 16/model
– Hot Blood 2/model ↘ 1/model
– Incendiary Ichor 2/model ↘ 1/model
• Threshing Engine:
– Starting cost 180 ↘ 160
– Horde Thresher 75 ↘ 60
– Legion Thresher 140 ↘ 115
– Fly and Light Troops 45 ↘ 30
– Roaming Hands 50 ↘ 40
– Mark of the Eternal Champion 40 ↘ 35
– Divining Snout 35 ↘ 20
– Whipcrack Tail 35 ↘ 30
– Horns of Hubris 25 ↘ 20
• Titanslayer Chariot:
– Starting cost 250 ↘ 220
– Digestive Vomit 30 ↘ 20
– Divining Snout 30 ↘ 20
– Segmented Shell 25 ↘ 20
– Stiff Upper Lip 15 ↘ 10
• Clawed Fiends:
– Starting cost 285 ↘ 275
– Additional models 93/model ↗ 96/model
– Broodmother 10/model ↗ 13/model
– Mesmerising Plumage 10/model ↘ 7/model
– Piercing Spike 9/model ↗ 12/model
– Darkhide 7/model ↘ 6/model
• Mageblight Gremlins:
– Additional models 57/model ↘ 39/model
– Piercing Spike 11/model ↘ 8/model
– Living Shield 9/model ↘ 8/model
– Unnatural Roots 7/model ↘ 6/model
– Greenfire Eyes 6/model ↘ 3/model
• Hoarders:
– Additional models 103/model ↗ 118/model
– Divining Snout 10/model ↘ 7/model
– Grasping Proboscis 9/model ↘ 5/model
– Unnatural Roots 9/model ↘ 8/model
– Kaleidoscopic Flesh 5/model ↘ 4/model
– Dextrous Tentacles 3/model
• Sirens:
– Additional models 32/model ↘ 28/model
– Hammer Hand 6/model ↗ 8/model
– Mesmerising Plumage 5/model ↘ 4/model
– Centipede Legs 3/model ↘ 2/model
– Hot Blood 3/model ↘ 2/model
• Blazing Glories:
– Starting cost 315 ↘ 280
– Stiff Upper Lip 25 ↘ 20
– Horns of Hubris 20 ↘ 15
– Brimstone Secretions 15 ↘ 10
– Cloven Hooves 15 ↘ 10
• Hope Harvester:
– Starting cost 260 ↗ 285
– Engine of Damnation 200 ↘ 120
– Sorcerous Antennae 45 ↘ 40
– Segmented Shell 35 ↘ 30
• Brazen Beasts:
– Red Haze 15/model ↗ 22/model
– Chitinous Scales 11/model ↘ 9/model
– Centipede Legs 9/model ↘ 8/model
– Incendiary Ichor 5/model ↘ 3/model
• Furies:
– Starting cost 150 ↗ 160
– Additional models 21/model ↘ 13/model
– Darkhide 3/model ↘ 2/model
– Mesmerising Plumage 3/model ↘ 2/model
– Red Haze 2/model ↘ 1/model
– Venom Sacs 2/model ↘ 1/model
• Veil Serpents:
– Starting cost 280 ↘ 265
– Additional models 80/model ↘ 58/model
• Bloat Flies:
– Starting cost 195 ↗ 290
– Additional models 92/model ↗ 100/model
– Minimum size 2/model ↗ 3/model
– Broodmother 13/model ↘ 12/model
– Kaleidoscopic Flesh 12/model ↘ 11/model
– Unhinging Jaw 5/model ↗ 7/model

**Comment by DarkSkyT9A** [comment]
Removing point changes from this large issue.

**Comment by DarkSkyT9A** [comment]
Invalidated by version 2.2 of DL
