### ISSUE TITLE
Orc& Goblin 0.99 update

### ISSUE THREAD

**Issue by gommo** [BSData/The-9th-Age#27]
I've opened up a pull request for this. Is this the best way for you or should I request write access to the repo?

**Comment by Arturius1** [comment]
Great work @gommo ! I've mentioned on 9th Age forum that you are now doing O&G file, so please check there from time to time for any mistakes that people find.

**Comment by gommo** [comment]
No worries. Is there other files that need looking after. Personally I have Daemons, UD & Empire as well. But my mate plays Vamps so I could look into that

**Comment by Arturius1** [comment]
if you can please do Vampire Covenant (besides that we lack Vermin Swarm and Ogre Khans)
