### ISSUE TITLE
[Anon] Bug report: Daemon Legions 2.0.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#282]
**File:** Daemon Legions 2.0.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** well... all the latest points and stats updates of course, but you already know.
my true request is a "point total" spot on the top bar for daemonic aspects to visualize how many points you've already spent

**Comment by DarkSkyT9A** [comment]
Duplicates #231
