### ISSUE TITLE
UD 0.99 Core Shabti

### ISSUE THREAD

**Issue by Nerachus** [BSData/The-9th-Age#31]
Can go beyond unit size 6 without a warning.
Should be disallowed if possible.

**Comment by Arturius1** [comment]
I am not familiar with that army.
Could you please elaborate more on what's need to be changed?
In the file I see two version of Shabti's, core and special choice.

**Comment by Nerachus** [comment]
If and only if the general is a Tomb Architect, one (1) unit with up to six models of Shabti may be taken as a core unit.

Greetings

Von meinem iPad gesendet

**Comment by Arturius1** [comment]
Thanks! Fixed now, will be published in next release.
