### ISSUE TITLE
[Anon] Bug report: Vampire Covenant.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#36]
**File:** Vampire Covenant.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** After adding a Vampire Count or a Vampire Courtier, it is not possible to add Bloodline Powers.

The bloodlines do not appear either.

**Comment by Arturius1** [comment]
Fixed in release 0.99.7
