### ISSUE TITLE
Some UD 0.99.2 bugs

### ISSUE THREAD

**Issue by Nerachus** [BSData/The-9th-Age#43]
Skeletons should not have the weapon option of halberds.
Shabti can only take a magical standard of up to 25 points.
Winged Reapers have a max unit size of 5, but i get a warning when I use more than 2 models.

**Comment by Arturius1** [comment]
Skeletons have access to halberds only if your Pharaoh general is Lord of the Barrow Legion.
Shabti - it is ok. Maybe you need to update your files @Nerachus ?
Winged Reapers - fixed.
