### ISSUE TITLE
ID: Pts are calculated double on Prophet for enchantments and Temple Lamassu Adept

### ISSUE THREAD

**Issue by rzmoz** [BSData/The-9th-Age#430]
Steps to Repro: 
1. Create list with Prophet incl enchantments that breaks the character limit
2. Note character points
3. Add enchantment of x pts

Observed: 
Pts spend in characters is increased by x * 2

Expected:
Pts spend in characters is increased by x

**Comment by DarkSkyT9A** [comment]
Hey @rzmoz have a look in the wiki on double counting bug. It explains how to fix this

**Comment by rzmoz** [comment]
@DarkSkyT9A Is it the wiki in this repo? I looked but I'm not sure wher the info is. Can you send a link/screendump, please?

**Comment by DarkSkyT9A** [comment]
Sorry, my mistake. I thought I wrote it down already, but didn't
