### ISSUE TITLE
Add Rules to all Offensive Profiles

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#445]
**Army Books**
- [ ] Beast Herds
- [ ] Dread Elves
- [x] Daemon Legions
- [ ] Dwarven Holds
- [ ] Empire of Sonnstahl
- [ ] Highborn Elves
- [x] Infernal Dwarves
- [ ] Kingdom of Equitaine
- [ ] Makhar
- [x] Ogre Khans
- [ ] Orcs and Goblins
- [ ] Saurian Ancients
- [ ] Sylvan Elves
- [ ] Undying Dynasties
- [x] Vampire Covenant
- [x] Vermin Swarm
- [ ] Warriors of the Dark Gods

**Auxiliary Books**
- [ ] Asklanders
- [ ] Makhar
- [ ] Cultists

**Comment by rzmoz** [comment]
Merged with #446
