### ISSUE TITLE
Add category modifiers for units getting additional categories delete multiple occurences of those units

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#458]
Note: This issue does not cover units which change their primary category (e.g. all options with "counts as core" conditions).

- [x] BH: Beast Chieftain
- [x] BH: Centaur Chieftain
- [x] BH: Soothsayer
- [x] BH: Wildhorn Herd
- [x] BH: Mongrel Herd
- [x] BH: Mongrel Raiders
- [x] BH: Centaurs
- [x] BH: Longhorn Herd
- [x] DL: Sentinel of Nukuja
- [x] DL: Kuulima's Deceiver
- [x] DL: Threshing Engine
- [x] DL: Blazing Glory
- [x] DE: Assassin Path of Silent Death
- [x] DH: Miners
- [x] DH: Rangers
- [x] EoS: Inquisitor
- [x] HE: –
- [x] ID: Citadel Guard
- [x] ID: Infernal Warriors
- [x] KoE: Duke
- [x] KoE: Damsel
- [x] KoE: Paladin 
- [x] Mak: Chariots
- [x] Mak: Flayers
- [x] Mak: Lancers
- [x] Mak: Nomadic Giant
- [x] Mak: Vassals
- [x] OK: Mercenary Veterans
- [x] SA: Skink Braves
- [x] SA: Skink Captain on Flying Mount
- [x] UD: Sand Stalkers
- [x] UD: Scarab Swarms
- [x] UD: Skeleton Archers
- [x] UD: Skeleton Cavalry
- [x] UD: Skeleton Chariots
- [x] UD: Skeletons
- [x] UD: Tomb Cataphracts
- [x] UD: Tomb Harbinger
- [X] VC Felwraith with Monstrous Revenant
- [X] WDG Chimera with Wings
- [X] WDG Chimera Mount with Wings

**Comment by rzmoz** [comment]
reg. ID: Hobgoblins. See commit https://github.com/BSData/The-9th-Age/pull/499/commits/7c989eee18fe9eeda333c9e5136488d6f5f6ea04

**Comment by DarkSkyT9A** [comment]
I suggest we wait a little before moving forward on this. Users don't seem to like the new behaviour, unless the entries are also moved into the correct primary category. On my first test, setting the primary category had some bad side effects and didn't work.

**Comment by rzmoz** [comment]
How about changing the title to: Move all shared entries into shared selections but keep multiple unit entries => easier maintenance while keeping the overview when making lists.

**Comment by DarkSkyT9A** [comment]
We could do that, but I have other things on my list, I'd rather do. If the "set primary category" feature would work properly, I think there is no downside anymore to single entries, as they would show up in their correct category (e.g. 8+ Goblin Raiders would be listed under core).

**Comment by rzmoz** [comment]
Sure, then how about continue with this task but leave out the ones where it changes primary category? The others (additional categories) work fine and as expected.

**Comment by DarkSkyT9A** [comment]
That's an excellent idea.

**Comment by rzmoz** [comment]
all seems to be done
