### ISSUE TITLE
[Anon] Bug report: The Vermin Swarm.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#47]
**File:** The Vermin Swarm.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Abomination Toxic Retaliation should now cost 25 points, not 30.

**Comment by Arturius1** [comment]
This was fixed in latest release, thanks for report!
