### ISSUE TITLE
Access to 9th Age data Repository

### ISSUE THREAD

**Issue by Karanadon** [BSData/The-9th-Age#49]
Hi Bombastian/Arturius, 

Can you please add me to the Repo so I can upload my files when done?

Cheers,
Karanadon.

**Comment by Arturius1** [comment]
@Karanadon I do not have power to give you access, but I can accept your files when you do a pull request. Also, for some reason, the updates won't work if you save the files as *.catz so keep in mind that you should only use *.cat

**Comment by Karanadon** [comment]
Ah ok, I will do pull requests from now on.
To save as .cat do I just do save as in the editor?

**Comment by Arturius1** [comment]
Yes, save as .cat in the editor.
Please do separate pulls for every army. (do not join two different armies in one pull)

**Comment by Arturius1** [comment]
@JimmyMalmer or @Toreador13 can you please invite @Karanadon into 9th Age team ?

**Comment by Toreador13** [comment]
Is he in the BSData Org? I can't invite him or find him I think until he is part of that org.

**Comment by Arturius1** [comment]
He is not. 
@amis92 could you please invite @Karanadon into BSData ?

**Comment by amis92** [comment]
Invited. @Karanadon, please don't forget to accept the invitation, otherwise you won't get any privileges. You can accept it either by clicking link in email you received, or on the [org homepage](https://github.com/BSData). Cheers!
