### ISSUE TITLE
[Anon] Bug report: orcsAndGoblins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#498]
**File:** orcsAndGoblins.catz

**BattleScribe version:** 2.03.09

**Platform:** Android

**Dropbox:** No

**Description:** Goblin raiders cannot be added to core. They can be in units of 8 or more.

**Comment by DarkSkyT9A** [comment]
Goblin Raiders count towards Core automatically if at least 8 models
