### ISSUE TITLE
WDG: Battleshrine and Sorceror

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#516]
Sorcerer on Battleshrine has no options for Banner enchantment

**Comment by rzmoz** [comment]
The banner enchantments are for the Shrine Priests (on a Battleshrine - not for the battleshrine itself. The Battleshrine for the sorcerer doesn't have any Shrine Priests)

**Comment by rzmoz** [comment]
Possible adjustment from Trophy Rack
