### ISSUE TITLE
Army General not recognized anymore 

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#546]
That issue with the error saying there is no General selected is with all factions I think, I'm getting it with OK, VS & SA

**Comment by rzmoz** [comment]
I've seen the same and I couldn't find any changes to the general selections so I believe it's a regression bug in BS itself ATM.

**Comment by DarkSkyT9A** [comment]
BattleScribe bug. Issue opened here: https://battlescribe.uservoice.com/forums/55066-battlescribe/suggestions/39066352-bug-report-shared-selection-entry-for-army-leader

**Comment by rzmoz** [comment]
Fixed in BS 2.03.16
