### ISSUE TITLE
Improve handling of Essence of a Free Mind

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#556]
*Introduce Essence path selection as Max 1 selection but without min setting. Only display when Essence is taken. Use this and the normal path for the path selection. Never hide the normal path selection.*

**Army Books**
- [x] Beast Herds
- [x] Dread Elves
- [x] Daemon Legions
- [x] Dwarven Holds
- [x] Empire of Sonnstahl
- [x] Highborn Elves
- [x] Infernal Dwarves
- [x] Kingdom of Equitaine
- [x] Ogre Khans
- [x] Orcs and Goblins
- [x] Saurian Ancients
- [x] Sylvan Elves
- [x] Undying Dynasties
- [x] Vampire Covenant
- [x] Vermin Swarm
- [x] Warriors of the Dark Gods

**Auxiliary Books**
- [x] Asklanders
- [x] Makhar
- [x] Cultists

**Comment by DarkSkyT9A** [comment]
@bbs-capelle I did it as an example for the Ogre Khans Shaman. Please look how I implemented it, and do the same for the others casters. If there are any questions, let me know.

**Comment by bbs-capelle** [comment]
For the wizard having to select only between 2 magic paths, do I change the current behaviour (no path selection)?

**Comment by DarkSkyT9A** [comment]
I would make it the same for all, meaning everybody has to select the paths even if there is no choice. Makes it more obvious which paths the wizard actually has.

**Comment by bbs-capelle** [comment]
Done :)
