### ISSUE TITLE
File Revision Numbers Are All Messed Up

### ISSUE THREAD

**Issue by Jonskichov** [BSData/The-9th-Age#57]
I'm not sure what's going on but the revision numbers in many of the 9th age files are going up/down all over the place as new versions are committed.

BattleScribe will only download new/updated files if it sees that the revision number on the server (here) is _higher_ than the revision number in the file it already has. If server revision no. is the same/lower than what it already has, it won't bother downloading the file.

This means that many of your updates are not making it down to users! Be careful to make sure your revision numbers increment as you release new versions of the files.

**Comment by Jonskichov** [comment]
An example:

Dwarven Holds are V1 on the site (https://battlescribedata.appspot.com/#/repo/The-9th-Age)

Going through the commits (https://github.com/BSData/The-9th-Age/commits/master/Dwarven%20Holds.cat) I see that it has been as high as 13! And went back down to 1 in the latest commit.

**Comment by Arturius1** [comment]
Aha! So that's what causing problems with updating.

Revisions going down is my doing - as I've decided to "reset" revision for DH file when the rules were updated from version 0.11 to 0.99

Thanks for head's up! Will now know to "up" them no matter what.

**Comment by Arturius1** [comment]
@Jonskichov in a few days version 1.0 rules will come out for all 9th Age files.

Do you think upping all revision numbers to, let's say, 100 is a good idea?
Or 40, since highest now is 35 for O&G file?
Or leave it as it is?

**Comment by Jonskichov** [comment]
The number can go as high as you need :)

If you want to "reset", an option would be to change the ID of the file, which would mean that as far as BattleScribe is concerned it is an entirely separate file. That said, just upping the file number would probably be best since otherwise everyone will end up with both versions...

I would suggest just upping the number to be higher than whatever it got to before, to ensure everyone gets the new version no matter which "old" version they got.

It doesn't matter if one file has a higher version than another, just that the version no. of a particular file goes up when you put out a new version (revision) of it :)

**Comment by Arturius1** [comment]
Just upped all revisions to 90, will make it 100 when armybooks 1.0 are released.
Our community has been reporting issues with updating, and we didn't know what caused them, so
once again many thanks for your message and support @Jonskichov ! :)
