### ISSUE TITLE
[Join Request] Wanting to join T9A Data support team

### ISSUE THREAD

**Issue by bbs-capelle** [BSData/The-9th-Age#583]
Could you accept my request to join the T9A team.
Hope this is how to to it :)
Thanks,

**Comment by artur-fijalkowski** [comment]
Great idea ;) You mean access to this repo for RW?

**Comment by bbs-capelle** [comment]
Yes, I'm part of the team to update T9A data files

**Comment by DarkSkyT9A** [comment]
@artur-fijalkowski can you grant @bbs-capelle the necessary access?

**Comment by Arturius1** [comment]
@bbs-capelle Invite sent !
