### ISSUE TITLE
DL: Unset magic path for Harbinger

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#654]
Harbingers of Father Chaos (DL) cannot unselect choice of magic path if you change your mind about them being a wizard.

**Army Books**
- [x] Daemon Legion (Harbinger of Father Chaos)
- [x] Infernal Dwarves (Prophet)
- [x] Sylvan Elves (Treefather Ancient, Dryad Ancient)
- [x] Vampire Covenant (Vampire Count, Vampire Courtier)

**Comment by bbs-capelle** [comment]
This issue is present for all characters being able to be a wizard has an option, I will add the list of all optional wizard character.

**Comment by bbs-capelle** [comment]
Harbinger of Father Chaos (DL)
Prophet (ID)
Treefather Ancient, Dryad Ancient (SE)
Vampire Count, Vampire Courtier (VC)

**Comment by DarkSkyT9A** [comment]
Vampire Counts are always Wizards, aren't they?

We probably need to think about a good solution there.

**Comment by bbs-capelle** [comment]
No the upgrade to apprentice is free but optional... (for Vampire counts)

**Comment by bbs-capelle** [comment]
There is no possibility to unselect an option depending on a condition right?
For those characters we could add an option "None" in Magic Path entry Group, selected it by default and add a condition to hide it when something else is selected, for example:
![image](https://user-images.githubusercontent.com/28262121/71244719-71463a00-2313-11ea-955e-20a69882a2ae.png)

**Comment by DarkSkyT9A** [comment]
I think the solution is to add a modifier for the "min 1 selections in parent" to 0, if the entry is not Wizard Apprentice, Adept, or Master. This way the section should allow selecting none. We should leave the hidden entry. Hidden acts in a way, that it stays visible if something is selected. This way you can select "none" and then it will be gone, which is good.
