### ISSUE TITLE
HE Path Selection with Essence

### ISSUE THREAD

**Issue by DarkSkyT9A** [BSData/The-9th-Age#686]
I bought Essence of a free mind for my mage and selected a path between Alchemy and Pyromancy. Whatever my choice (I can only select one), BS keeps repeating I need one more path, which I can't select without losing the other one.

**Comment by bbs-capelle** [comment]
This is working as planned, the "Essence of a Free Mind Magic Path" section appears when the object is selected. I think he didn't saw the new section.
