### ISSUE TITLE
Can someone give me permission to push local changes

### ISSUE THREAD

**Issue by Maetco** [BSData/The-9th-Age#70]
The title. Even though I have used Github in the past on two different community projects, I'm still a total noob when it comes to Github so if my request seems idiotic, please help me to help you with the catalogues.

**Comment by Arturius1** [comment]
Hello!
Thanks for your offer but since 1.0 release we are mainly fixing errors now. If you still wish to help  please first fork a repository and do some pull requests. If they are OK we can push them to the master.
