### ISSUE TITLE
heroes+lords percentage count

### ISSUE THREAD

**Issue by Arturius1** [BSData/The-9th-Age#72]
@Jonskichov 

We encountered a problem that we cannot overcome, and would like to ask for your help:

our game rules state that Lords+Heroes choice is limited to max 50% points
Gamesystem has it coded that Heroes decrement maxPercentage by 1 (repeating) 1 times for every 1 percent in Lords
![screenshot_8 1](https://cloud.githubusercontent.com/assets/17968409/15782512/ee1096ea-29aa-11e6-9728-30a5f08f88bb.jpg)

This however causes that no error flag is shown when Lords+Heroes choices take 1010pts in 2000pts list. 
![screenshot_9 1](https://cloud.githubusercontent.com/assets/17968409/15782551/13f58b04-29ab-11e6-8d73-295d47a64045.jpg)

Error flag begins to show from 1011 pts (while it should show from 1001 pts).
![screenshot_10 1](https://cloud.githubusercontent.com/assets/17968409/15782577/2a485378-29ab-11e6-8a91-06a991823183.jpg)

Any idea what we are doing wrong / what is causing this issue ?

**Comment by Arturius1** [comment]
@amis92 maybe you could help or know why is it like that ?

**Comment by amis92** [comment]
Seems like a classic rounding issue. My bet is that since 650/2000 is 0.325 your modifier on Heroes is triggered 50 - 32 = 18 times (as seen on error line) which then perfectly agrees with 360, but not 361 points of Heroes. There's nothing you can do except merge those categories into single Lords+Heroes. :/

**Comment by Arturius1** [comment]
Thanks for answer !

**Comment by Arturius1** [comment]
We are still encountering this problem - and to be honest it's quite problematic for us.

@amis92 do you know if this issue will be corrected in Battlescribe v.2.0 ?
