### ISSUE TITLE
New game system file

### ISSUE THREAD

**Issue by Arturius1** [BSData/The-9th-Age#78]
@amis92 

In a few days our game will receive a major update that requires an entire rewrite of game system file.
Is it possible to upload the new file to the repository (with a new ID) and at the same time keep the old one?

Then we would have:
Fantasy Battles The 9th Age.gstz
and
Fantasy Battles The 9th Age v.1.2.gstz

if not should we delete all the old files and upload new ones, with new IDs, starting from revision 1?

**Comment by amis92** [comment]
Yes, you have to have only one .gst (not .gstz!) file per repo. That means always the newest. For time being you can create another branch for new system WIP (it won't be available on AppSpot site).

So yes, essentially, when we are talking about huge changes, you should change gst ID (and all catalogue IDs too), so essentially re-upload new files.
