### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by beckian** [BSData/The-9th-Age#90]
Hello,

I have recently joined the HoRKT team and have been working on a couple of catalogues there. I have an interest in getting the Vermin Swarm catalogue updated for the V1.2 9th age and would like to help out as much as I can.

**Comment by Karanadon** [comment]
If you are keen to get on to it feel free to make a file for VS and submit via pull request.

@Arturius1 sound like a good idea?

**Comment by beckian** [comment]
I don't think I have permission to do a pull request, I have tried but maybe I am doing something wrong. I suppose these catalogues need updating to BS2.0 too?

**Comment by Arturius1** [comment]
@beckian we could use your help since VS is one of the few files left to-do.
Please download our latest gamesystem and other files and try to make VS in similar manner.

Do you have an account on 9th Age Forum? If yes, what is your nick there?

Membership request approved. The user has been added to the team.

**Comment by beckian** [comment]
I have signed up to T9A forum now - beckian there too. Are we updating to battlescribe 2.0?  Can we put the common shared rules into the gst?

**Comment by Arturius1** [comment]
Great!
It's nice to have you in our crew ! Here is the link to forum Battlescribe thread, please take a look when you have time
http://www.the-ninth-age.com/index.php?thread/639-battlescribe-files/&pageNo=1

About 2.0 - no, we are not updating - Vermin Swarm is the last file to be done in previous version of BS.
When it's completed we will focus on 2.0. For now please work in BS 1.15.07

Also please modify your VS file @beckian as it gives me this every time upon trying to create a rooster
Message:
net.battlescribe.a.c.e: The Vermin Swarm.cat was corrupted and has been deleted.
